### PR TITLE
README: add deprecation notice

### PR DESCRIPTION
**Pull request by dcousens**

### CODE REVIEW

**Comment by dcousens** [comment]
Related to https://github.com/cryptocoinjs/sha512/issues/2

**Comment by jprichardson** [comment]
Why deprecate?

**Comment by fanatid** [comment]
sha512 in sha.js looks more clear?

**Comment by dcousens** [comment]
This is inline with https://github.com/cryptocoinjs/sha256

**Comment by dcousens** [comment]
ping @jprichardson

**Comment by dcousens** [comment]
bump

**Comment by jprichardson** [comment]
I gotta ask... why is this particular issue so important to you? I've never had someone so adamant about deprecating a package before.

**Comment by dcousens** [comment]
@jprichardson its in my PR list - https://github.com/pulls,  I try to empty it.  I'd rather close than have it linger.

**Comment by jprichardson** [comment]
Ah, I didn't even know https://github.com/pulls existed!

**Comment by dcousens** [comment]
There goes your productivity for the day then :P

**Comment by dcousens** [comment]
Don't even start on https://github.com/issues

**Comment by jprichardson** [comment]
> Don't even start on https://github.com/issues

OMG. Ignorance was bliss! haha

**Pull request merged**
